############################
## CHANGE THESE
############################

baseURL: "https://droidzemo.github.io/qbutclone"
title: qbutclone

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
